In [7]:
import pennylane as qml
from pennylane import numpy as np

n_qubits = 3
wires = list(range(n_qubits))

dev = qml.device("default.qubit", wires=n_qubits)

@qml.qnode(dev)
def circuit():
    qml.BasisState(np.array([1, 0, 1]), wires=wires)
    return qml.state()

# Run to verify the prepared state
final_state = circuit()
print("Prepared statevector:", final_state)

# Get matrix representation
prep_gate = qml.BasisState(np.array([0, 1, 0]), wires=wires)
script = qml.tape.QuantumScript(ops=[prep_gate])
matrix = qml.matrix(script, wire_order=wires)

print("\nMatrix representation of qml.BasisState([1,1,1]):")
print(matrix)


Prepared statevector: [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j 0.+0.j]

Matrix representation of qml.BasisState([1,1,1]):
[[0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]]
